
users: 
  - user: "Uli Kaulfuss"
    tags: 
      - "uli"
      - "uli kaulfu"
    email: "ulikaulfuss@k-datacenter.de"
    folder: "Daten Uli"
  - user: "Lara Kaulfuss"
    tags: 
      - "lara"
      - "lara kaulfu"
    email: "larakaulfuss@k-datacenter.de"
    folder: "Daten Lara"
  - user: "Tim Kaulfuss"
    tags: 
      - "tim"
      - "tim kaulfu"
    email: "timkaulfuss@k-datacenter.de"
    folder: "Daten Tim"
  - user: "Corinna Kaulfuss"
    tags: 
      - "corinna"
      - "corinna kaulfu"
    email: "corinnakaulfuss@k-datacenter.de"
    folder: "Daten Corinna"


catch_all_user:
  user: "catchall"
  email : "kir@k-datacenter.de"
  folder : ""